---

  - name: "Update APT cache"
    apt: update_cache=yes

  - name: Install common packages
    apt: name={{ item }} state=present
    with_items:
      - vim
      - wget
      - curl
      - zip
      - unzip      
      - sudo   

  # we only need this for older-ish kernels which require kernel upgrade    
  - include: add-layerfs-support.yml
    when: ansible_kernel | match("3.\d.*-generic")
